

/**
 * 1. DISPATCH CHANGES / SYNC AND ASYNC
 * 2. NOTIFY ONLY FOR CHANGES REGARDING A COMPONENT
 * 2.A. HAVE VIEWS ON GLOBAL STATE
 * 2.B. VIEW HAS QUERIES & DISPATCHERS - VIEW IS BINDED TO A COMPONENT, A COMPONENT HAS JUST A VIEW
 * 3. PERFORM QUERIES
 * 4. TYPED GLOBAL STATE
 * 5. PERFORM PUB/SUB NOTIFICATIONS
 * 6. GLOBAL STATE - WRAPPER OVER MODEL AND DOCK MANAGER
  * 
  * 7. STATE VIEW: QUERIES, NOTIFICATIONS, DISPATCHERS, BINDING TO A COMPONENT
  * 8. VIEW REGISTRY - VIEWS ARE REGISTERED IN THE STATE MODEL AND QUERIED BY NAME
  * 8. STATE MODEL: HOLDS COMMUNICATION AMONG VIEWS, CONTAINS THE DOCKING MODEL, PERFORMS PERSITENCE SAVING
  * 9. NOTIFICATION MANAGER
  * 10. MODEL ITSELF HAS NOTIFICATIONS ABOUT DATA CHANGES WHICH DRIVES THE STATE VIEW NOTICATIONS
  *  
  * 
 * 7. DOM HELPER - CACHE DOM CHANGES
 * 
 * 8. PERSITENCE
 *   8.A. GLOBAL STATE
 *   8.B. UI COMPONENT TREE
 * 
 */